### ISSUE TITLE
Not cleared desktop and icons file after unregister a AppImage

### ISSUE THREAD

**Issue by blackPantherOS** [probonopd/AppImageKit#329] opened 2017-01-14 21:52 UTC
Hi, I try made a system integrated RPM package to blackPanther OS RPM based Hungarian distro. I have the follow little problem:

**Action: AppImage  move to dest dir :**

> install: /home/vector/.local/share/applications/appimagekit_c6c7075275428cf778551c85c82fb0d7-Kaku.desktop
> install: /home/vector/.local/share/icons/default/128x128/apps/appimagekit_c6c7075275428cf778551c85c82fb0d7_Kaku.png
> Installed: /home/vector/.local/share/icons/default/128x128/apps/appimagekit_c6c7075275428cf778551c85c82fb0d7_Kaku.png
> install: /home/vector/.local/share/icons/default/16x16/apps/appimagekit_c6c7075275428cf778551c85c82fb0d7_Kaku.png
> Installed: /home/vector/.local/share/icons/default/16x16/apps/appimagekit_c6c7075275428cf778551c85c82fb0d7_Kaku.png
> install: /home/vector/.local/share/icons/default/24x24/apps/appimagekit_c6c7075275428cf778551c85c82fb0d7_Kaku.png
> Installed: /home/vector/.local/share/icons/default/24x24/apps/appimagekit_c6c7075275428cf778551c85c82fb0d7_Kaku.png
> install: /home/vector/.local/share/icons/default/256x256/apps/appimagekit_c6c7075275428cf778551c85c82fb0d7_Kaku.png
> Installed: /home/vector/.local/share/icons/default/256x256/apps/appimagekit_c6c7075275428cf778551c85c82fb0d7_Kaku.png
> install: /home/vector/.local/share/icons/default/32x32/apps/appimagekit_c6c7075275428cf778551c85c82fb0d7_Kaku.png
> Installed: /home/vector/.local/share/icons/default/32x32/apps/appimagekit_c6c7075275428cf778551c85c82fb0d7_Kaku.png
> install: /home/vector/.local/share/icons/default/48x48/apps/appimagekit_c6c7075275428cf778551c85c82fb0d7_Kaku.png
> Installed: /home/vector/.local/share/icons/default/48x48/apps/appimagekit_c6c7075275428cf778551c85c82fb0d7_Kaku.png
> install: /home/vector/.local/share/icons/default/64x64/apps/appimagekit_c6c7075275428cf778551c85c82fb0d7_Kaku.png
> Installed: /home/vector/.local/share/icons/default/64x64/apps/appimagekit_c6c7075275428cf778551c85c82fb0d7_Kaku.png
> install: /home/vector/.local/share/icons/default/512x512/apps/appimagekit_c6c7075275428cf778551c85c82fb0d7_Kaku.png
> Installed: /home/vector/.local/share/icons/default/512x512/apps/appimagekit_c6c7075275428cf778551c85c82fb0d7_Kaku.png
> Set /home/vector/Downloads/Kaku-1.8.5-ia32.AppImage executable
> 

**Action: Move out the AppImage:**
> -> UNREGISTER /home/vector/Downloads/Kaku-1.8.5-ia32.AppImage
> get_thumbnail_path: /home/vector/.cache/thumbnails/normal/c6c7075275428cf778551c85c82fb0d7.png
> get_thumbnail_path: /home/vector/.cache/thumbnails/large/c6c7075275428cf778551c85c82fb0d7.png
> 

**Still desktop file here:**
> vector@core4〉~/Downloads〉cat /home/vector/.local/share/applications/appimagekit_c6c7075275428cf778551c85c82fb0d7-Kaku.desktop
> [Desktop Entry]
> Name=Kaku
> Comment=The next generation music client
> Exec=/home/vector/Downloads/Kaku-1.8.5-ia32.AppImage
> Terminal=false
> Type=Application
> Icon=appimagekit_c6c7075275428cf778551c85c82fb0d7_Kaku
> X-AppImage-Version=1.8.5
> X-AppImage-BuildId=91cfd940-bb04-11a6-06d1-7d9c2db84c31
> TryExec=/home/vector/Downloads/Kaku-1.8.5-ia32.AppImage
> X-AppImage-Comment=Generated by appimaged continuous
> X-AppImage-Identifier=c6c7075275428cf778551c85c82fb0d7
> 
>

**Comment by probonopd** [comment] 2017-01-22 13:58
Cannot reproduce this using `xubuntu-16.04-desktop-amd64.iso` and appimaged version continuous-1-g7ca62f3.

**Comment by probonopd** [comment] 2017-01-28 12:31
@blackPantherOS can you still reproduce this? If so, please let me know which Live ISO I could use to test this.

**Comment by blackPantherOS** [comment] 2017-01-28 19:56
Sorry, I'm very busy . I will try tomorrow on a fresh installed blackPanther OS system . Thanks

**Comment by blackPantherOS** [comment] 2017-01-29 16:09
Hi again! Thanks to your time, I tried reprocedure this on clean installation. This bug maybe is invalid, i can't repeat, sorry!

**Comment by probonopd** [comment] 2017-01-29 16:25
No problem. Closing. Feel free to reopen if the problem appears again.

**Closed by probonopd** 2017-01-29 16:25 UTC
Labels: bug

**Comment by blackPantherOS** [comment] 2017-01-29 16:28
Ok, Thx
I made a demo video howto work under blackPanther OS, if interest for you
https://www.youtube.com/watch?v=zDBuG0v_rTA
