### ISSUE TITLE
[32-bit] appimaged segfaults

### ISSUE THREAD

**Issue by probonopd** [probonopd/AppImageKit#309] opened 2016-12-03 19:41 UTC
As discovered [here](https://github.com/probonopd/AppImageKit/pull/307#issuecomment-264585565), the 32-bit version of `appimaged` segfaults whereas the 64-bit one does not.

```
./appimaged-Intel_80386.AppImage --install

/home/me/.local/bin/appimaged
_________________________

-> REGISTER /home/me/.local/bin/appimaged
squashfs based type 2 AppImage
Segmentation fault
```

AppImage containing an unstripped version of appimaged attached.

[appimaged-Intel_80386.AppImage.zip](https://github.com/probonopd/AppImageKit/files/629080/appimaged-Intel_80386.AppImage.zip)

Perhaps @orivej can give me some hint using his magic debugging powers?

**Comment by probonopd** [comment] 2016-12-03 19:44
Note: 64-bit AppImages are present in the system. So it might be an issue with a 32-bit system trying to read 64-bit AppImages in the wrong way (e.g., getting the wrong offsets for ELF sections).

**Comment by orivej** [comment] 2016-12-03 22:24
Could you rebuild appimaged with the `-g` flag?
```patch
 # appimaged, an optional component
-cc -std=gnu99 ...
+cc -g -std=gnu99 ...
```

**Comment by probonopd** [comment] 2016-12-03 23:16
Attached.

[appimaged-Intel_80386.AppImage.zip](https://github.com/probonopd/AppImageKit/files/629190/appimaged-Intel_80386.AppImage.zip)

**Comment by orivej** [comment] 2016-12-04 01:14
I do not know yet how this happens but when `squash_get_matching_files` instantiates `sqfs_traverse trv` it believes that `sqfs_off_t trv.entry.offset, trv.entry.next_offset` are 4 bytes long each, but `sqfs_traverse_next` called from `squash_get_matching_files` believes that they are 8 bytes long each. I.e. for `squash_get_matching_files` trv.entry field offsets and sizes are:
```c
struct sqfs_dir_entry {
/* 0 8 */       sqfs_inode_id inode;
/* 8 4 */       sqfs_inode_num inode_number;
/* 12 4 */      int type;
/* 16 4 */      char * name;
/* 20 4 */      size_t name_size;
/* 24 4 */      sqfs_off_t offset;
/* 28 4 */      sqfs_off_t next_offset;
}
```
and for `squash_get_matching_files` they are
```c
struct sqfs_dir_entry {
/* 0 8 */       sqfs_inode_id inode;
/* 8 4 */       sqfs_inode_num inode_number;
/* 12 4 */      int type;
/* 16 4 */      char * name;
/* 20 4 */      size_t name_size;
/* 24 8 */      sqfs_off_t offset;
/* 32 8 */      sqfs_off_t next_offset;
}
```

**Comment by orivej** [comment] 2016-12-04 01:46
`gcc -E` could help you trace where `sqfs_off_t` definition comes from. For example, replace `cc -std=gnu99 ... -o appimaged` with `cc -std=gnu99 ... -E > appimaged.c`, do the same for the squashfuse compilation command that mentions `traverse.c`, and compare the origin of `sqfs_off_t` in the generated .c files, or publish them here.

**Comment by probonopd** [comment] 2016-12-04 10:49
The output of the first command is attached; I am somewhat lost on the instructions for the second one ("do the same for the squashfuse compilation command that mentions traverse.c)"). What exactly do I need to run?

```
# grep -r "traverse\.c" ..
Binary file ../squashfuse/libsquashfuse_la-traverse.o matches
Binary file ../squashfuse/.libs/libsquashfuse_ll.a matches
Binary file ../squashfuse/.libs/libsquashfuse.a matches
Binary file ../squashfuse/.libs/libsquashfuse_la-traverse.o matches
../squashfuse/.deps/libsquashfuse_la-traverse.Plo:libsquashfuse_la-traverse.lo: traverse.c /usr/include/stdc-predef.h \
../squashfuse/Makefile:	decompress.c xattr.c hash.c stack.c traverse.c util.c \
../squashfuse/Makefile:libsquashfuse_la-traverse.lo: traverse.c
../squashfuse/Makefile:	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libsquashfuse_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT libsquashfuse_la-traverse.lo -MD -MP -MF $(DEPDIR)/libsquashfuse_la-traverse.Tpo -c -o libsquashfuse_la-traverse.lo `test -f 'traverse.c' || echo '$(srcdir)/'`traverse.c
../squashfuse/Makefile:#	$(AM_V_CC)source='traverse.c' object='libsquashfuse_la-traverse.lo' libtool=yes \
../squashfuse/Makefile:#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libsquashfuse_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o libsquashfuse_la-traverse.lo `test -f 'traverse.c' || echo '$(srcdir)/'`traverse.c
../squashfuse/Makefile.in:	decompress.c xattr.c hash.c stack.c traverse.c util.c \
../squashfuse/Makefile.in:libsquashfuse_la-traverse.lo: traverse.c
../squashfuse/Makefile.in:@am__fastdepCC_TRUE@	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libsquashfuse_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT libsquashfuse_la-traverse.lo -MD -MP -MF $(DEPDIR)/libsquashfuse_la-traverse.Tpo -c -o libsquashfuse_la-traverse.lo `test -f 'traverse.c' || echo '$(srcdir)/'`traverse.c
../squashfuse/Makefile.in:@AMDEP_TRUE@@am__fastdepCC_FALSE@	$(AM_V_CC)source='traverse.c' object='libsquashfuse_la-traverse.lo' libtool=yes @AMDEPBACKSLASH@
../squashfuse/Makefile.in:@am__fastdepCC_FALSE@	$(AM_V_CC@am__nodep@)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libsquashfuse_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o libsquashfuse_la-traverse.lo `test -f 'traverse.c' || echo '$(srcdir)/'`traverse.c
../squashfuse/Makefile.am:	decompress.c xattr.c hash.c stack.c traverse.c util.c \
../squashfuse/Makefile.am.orig:	decompress.c xattr.c hash.c stack.c traverse.c util.c \
../squashfuse/win/squashfuse_ls.vcxproj.filters:    <ClCompile Include="..\traverse.c">
../squashfuse/win/squashfuse_ls.vcxproj:    <ClCompile Include="..\traverse.c" />
```

[_appimaged.c.zip](https://github.com/probonopd/AppImageKit/files/629413/_appimaged.c.zip)

**Comment by orivej** [comment] 2016-12-04 11:07
If you run `make AM_DEFAULT_VERBOSITY=1` in `squashfuse` (after `make clean`), it will print compilation commands. On my system one command with `traverse.c` is `gcc -DHAVE_CONFIG_H -I. -I/usr/lib//include -Wall -g -O2 -MT libsquashfuse_la-traverse.lo -MD -MP -MF .deps/libsquashfuse_la-traverse.Tpo -c traverse.c -o libsquashfuse_la-traverse.o`, but you should copy it from the output of make rather than from here in case it is different, and replace `-o libsquashfuse_la-traverse.o` with `-E > /tmp/traverse.c`.

**Comment by probonopd** [comment] 2016-12-04 11:16
On Ubuntu 16.04 64-bit, getting

```
gcc -DHAVE_CONFIG_H -I. -I/usr/lib//include -Wall -g -O2 -MT libsquashfuse_la-traverse.lo -MD -MP -MF .deps/libsquashfuse_la-traverse.Tpo -c traverse.c  -fPIC -DPIC -o .libs/libsquashfuse_la-traverse.o
```

Hence running

```
gcc -DHAVE_CONFIG_H -I. -I/usr/lib//include -Wall -g -O2 -MT libsquashfuse_la-traverse.lo -MD -MP -MF .deps/libsquashfuse_la-traverse.Tpo -c traverse.c  -fPIC -DPIC -E > _traverse.c
```

Output [attached](https://github.com/probonopd/AppImageKit/files/629427/_traverse.c.zip).

Should I repeat this on the 32-bit system?

**Comment by orivej** [comment] 2016-12-04 11:18
Yes, the point is to know how on the 32-bit system `off_t` turned out to be 8 bytes long.

**Comment by probonopd** [comment] 2016-12-04 13:16
Here are the results from `ubuntu-16.04.1-desktop-i386.iso`:
[32-bit.zip](https://github.com/probonopd/AppImageKit/files/629533/32-bit.zip)

**Comment by orivej** [comment] 2016-12-04 13:55
It looks like `appimaged` compilation command should include `-D_FILE_OFFSET_BITS=64`. Then you would see `typedef __off64_t off_t;` instead of `typedef __off_t off_t;` in the generated `_appimaged.c`, and appimaged will be compatible with squashfuse.

**Comment by probonopd** [comment] 2016-12-04 15:12
@orivej also on a 32-bit system?

**Comment by orivej** [comment] 2016-12-04 15:26
Yes, it may and should have no effect on a 64-bit system.

We better extend Travis CI check with a build of `appimaged`. CentOS 6 lacks static inotifytools, and when I installed them from source, appimaged was segfaulting during inotify setup. Maybe we should use 32 bit Ubuntu docker image?

**Comment by probonopd** [comment] 2016-12-04 15:29
> We better extend Travis CI check with a build of appimaged. 

Travis CI should already now build appimaged, but does not run it. Do you mean we should run it on Travis? Good idea indeed. We already exercise appimagetool a bit by having it produce an AppImage, and we exercice runtime by using an AppImage to make another AppImage... :-)

**Comment by probonopd** [comment] 2016-12-04 15:43
Unfortunately still getting the segfault on 32-bit. 

```
me@host:~$ /home/me/.local/bin/appimaged --version
Version: continuous-1-g188d235
me@host:~$ /home/me/.local/bin/appimaged
Segmentation fault
```

[strace.log.txt](https://github.com/probonopd/AppImageKit/files/629620/strace.log.txt)

**Comment by orivej** [comment] 2016-12-04 16:36
This is another issue that should be fixed by #317.
```
char buffer[4];
buffer[4] = 0;
```
is not ok, but segfaults only on 32-bit due to alignment.

**Closed** 2016-12-04 16:46 UTC
Labels: bug

**Comment by probonopd** [comment] 2016-12-04 17:16
What should I say, you are a genius! Works. :-)

Can you give me some recommendations on how to learn your C debugging wizardry?

**Comment by orivej** [comment] 2016-12-04 21:00
I am not sure, but I guess that it is time efficient and rewarding to learn debugging by trying to solve your problems as they occur, rather than preparing beforehand (even if it takes tens of hours to solve the simplest problems), if you approach them with a certain mindset that I'll attempt to describe.

You begin with a coherent model of how your program should behave in time, no matter how simplistic the model is, and observe its discrepancy with reality. Then you research the cause of discrepancy, both by enhancing the model and by learning about reality. If your program has terminated with a segfault, you will have to learn what signals are, that they may be sent by the operating system, and when it sends sigsegv; then you will know that your program did not reach a normal exit, and will demand what point did it reach; then you will learn about ptrace, gdb, its commands "run" and "backtrace" and "print"; then you will demand to know file names and line numbers at the termination point, and learn about compiling with debug info and installing packages providing debug info; then, for example, you will see variables with corrupted values, and seek to know what corrupted them, and learn about breakpoints and watchpoints and single-stepping; then source code may still not give the cause of discrepancy, and you will learn assembly language, program memory layout, typical correspondences between C and assembly constructs, compilation of object files and their linking into libraries and programs...

Personally I almost never was learning debugging in particular, unless reading gdb manual counts, but I was curious about how native compilers work, and I programmed in assembler for the fun of it and had to learn what to do when my programs crashed, and I paid attention to the capabilities of debuggers in languages (e.g. Common Lisp), IDEs, and browsers to adjust my expectations of what is possible with the right tools.
