### ISSUE TITLE
Installation fails on Ubuntu Yakkety

### ISSUE THREAD

**Issue by thopiekar** [probonopd/AppImageKit#221] opened 2016-08-28 11:14 UTC
Followed the README.md and tried to build AppImageKit from source, but I get this error message during build. Is there something missing here?

```
[ 25%] Performing download step (git clone) for 'AppImageKit'
Cloning into 'AppImageKit'...
Note: checking out 'origin/master'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 7bd1c72... Merge pull request #218 from joaomoreno/patch-2
[ 50%] No patch step for 'AppImageKit'
[ 50%] Performing update step for 'AppImageKit'
Current branch HEAD is up to date.
[ 75%] Performing configure step for 'AppImageKit'
-- The C compiler identification is GNU 6.2.0
-- Check for working C compiler: /usr/lib/icecc/bin/cc
-- Check for working C compiler: /usr/lib/icecc/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found glib-2.0: /usr/include/glib-2.0, /usr/lib/x86_64-linux-gnu/libglib-2.0.so
-- Configuring done
-- Generating done
-- Build files have been written to: /media/hdd/home/thopiekar/Projekte/eclipse-Ultimaker/cura-build-environment/build/AppImageKit-prefix/src/AppImageKit
[ 75%] Performing build step for 'AppImageKit'
Scanning dependencies of target isofs
[ 12%] Building C object CMakeFiles/isofs.dir/isofs.c.o
In file included from /usr/include/stdio.h:27:0,
                 from /media/hdd/home/thopiekar/Projekte/eclipse-Ultimaker/cura-build-environment/build/AppImageKit-prefix/src/AppImageKit/isofs.c:24:
/usr/include/features.h:148:3: warning: #warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Wcpp]
 # warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"
   ^~~~~~~
[ 25%] Linking C static library libisofs.a
[ 25%] Built target isofs
Scanning dependencies of target fuseiso
[ 37%] Building C object CMakeFiles/fuseiso.dir/fuseiso.c.o
/media/hdd/home/thopiekar/Projekte/eclipse-Ultimaker/cura-build-environment/build/AppImageKit-prefix/src/AppImageKit/fuseiso.c: In function 'del_mount_point':
/media/hdd/home/thopiekar/Projekte/eclipse-Ultimaker/cura-build-environment/build/AppImageKit-prefix/src/AppImageKit/fuseiso.c:78:14: warning: implicit declaration of function 'rmdir' [-Wimplicit-function-declaration]
     int rc = rmdir(mount_point);
              ^~~~~
/media/hdd/home/thopiekar/Projekte/eclipse-Ultimaker/cura-build-environment/build/AppImageKit-prefix/src/AppImageKit/fuseiso.c: In function 'isofs_init':
/media/hdd/home/thopiekar/Projekte/eclipse-Ultimaker/cura-build-environment/build/AppImageKit-prefix/src/AppImageKit/fuseiso.c:110:5: warning: implicit declaration of function 'run_when_fuse_fs_mounted' [-Wimplicit-function-declaration]
     run_when_fuse_fs_mounted();
     ^~~~~~~~~~~~~~~~~~~~~~~~
/media/hdd/home/thopiekar/Projekte/eclipse-Ultimaker/cura-build-environment/build/AppImageKit-prefix/src/AppImageKit/fuseiso.c: In function 'normalize_name':
/media/hdd/home/thopiekar/Projekte/eclipse-Ultimaker/cura-build-environment/build/AppImageKit-prefix/src/AppImageKit/fuseiso.c:55:5: warning: ignoring return value of 'realpath', declared with attribute warn_unused_result [-Wunused-result]
     realpath(fname, abs_fname);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~
[ 50%] Linking C static library libfuseiso.a
[ 50%] Built target fuseiso
Scanning dependencies of target runtime
[ 62%] Building C object CMakeFiles/runtime.dir/runtime.c.o
/media/hdd/home/thopiekar/Projekte/eclipse-Ultimaker/cura-build-environment/build/AppImageKit-prefix/src/AppImageKit/runtime.c: In function 'main':
/media/hdd/home/thopiekar/Projekte/eclipse-Ultimaker/cura-build-environment/build/AppImageKit-prefix/src/AppImageKit/runtime.c:211:7: warning: implicit declaration of function 'g_build_filename' [-Wimplicit-function-declaration]
     ? g_build_filename(g_get_home_dir(), ".cache", NULL)
       ^~~~~~~~~~~~~~~~
/media/hdd/home/thopiekar/Projekte/eclipse-Ultimaker/cura-build-environment/build/AppImageKit-prefix/src/AppImageKit/runtime.c:211:24: warning: implicit declaration of function 'g_get_home_dir' [-Wimplicit-function-declaration]
     ? g_build_filename(g_get_home_dir(), ".cache", NULL)
                        ^~~~~~~~~~~~~~
/media/hdd/home/thopiekar/Projekte/eclipse-Ultimaker/cura-build-environment/build/AppImageKit-prefix/src/AppImageKit/runtime.c:212:7: warning: implicit declaration of function 'g_strdup' [-Wimplicit-function-declaration]
     : g_strdup(getenv("XDG_CACHE_HOME")));
       ^~~~~~~~
/media/hdd/home/thopiekar/Projekte/eclipse-Ultimaker/cura-build-environment/build/AppImageKit-prefix/src/AppImageKit/runtime.c:210:18: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
   xdg_cache_home = (getenv("XDG_CACHE_HOME") == NULL
                  ^
/media/hdd/home/thopiekar/Projekte/eclipse-Ultimaker/cura-build-environment/build/AppImageKit-prefix/src/AppImageKit/runtime.c:257:5: warning: ignoring return value of 'read', declared with attribute warn_unused_result [-Wunused-result]
     read (keepalive_pipe[0], &c, 1);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/media/hdd/home/thopiekar/Projekte/eclipse-Ultimaker/cura-build-environment/build/AppImageKit-prefix/src/AppImageKit/runtime.c:318:9: warning: ignoring return value of 'system', declared with attribute warn_unused_result [-Wunused-result]
         system(mkcmd);
         ^~~~~~~~~~~~~
[ 75%] Linking C executable runtime
[ 75%] Built target runtime
Scanning dependencies of target AppImageAssistant
cp: cannot stat '/media/hdd/home/thopiekar/Projekte/eclipse-Ultimaker/cura-build-environment/build/AppImageKit-prefix/src/AppImageKit/binary-dependencies/x86_64/libjte*': No such file or directory
rm: cannot remove './AppImageAssistant': No such file or directory
Creating /media/hdd/home/thopiekar/Projekte/eclipse-Ultimaker/cura-build-environment/build/AppImageKit-prefix/src/AppImageKit/AppImageAssistant ...
xorriso 0.5.6 : RockRidge filesystem manipulator, libburnia project.

xorriso : WARNING : -volid text does not comply to ISO 9660 / ECMA 119 rules
xorriso : UPDATE : Thank you for being patient for 1 seconds
Drive current: -dev '/media/hdd/home/thopiekar/Projekte/eclipse-Ultimaker/cura-build-environment/build/AppImageKit-prefix/src/AppImageKit/AppImageAssistant'
Media current: stdio file, overwriteable
Media status : is blank
Media summary: 0 sessions, 0 data blocks, 0 data,  170g free
Volume id    : 'ISOIMAGE'
New volume id: 'AppImage'
xorriso : UPDATE : 49 files added in 1 seconds
Added to ISO image: directory '/'='/media/hdd/home/thopiekar/Projekte/eclipse-Ultimaker/cura-build-environment/build/AppImageKit-prefix/src/AppImageKit/AppImageAssistant.AppDir'
xorriso : UPDATE : 1 files added in 1 seconds
Added to ISO image: file '/.DirIcon'='/media/hdd/home/thopiekar/Projekte/eclipse-Ultimaker/cura-build-environment/build/AppImageKit-prefix/src/AppImageKit/AppImageAssistant.AppDir/AppImageAssistant.png'
xorriso : UPDATE : 44 file filters processed in 1 seconds
xorriso : UPDATE : Writing:        199s   32.7%   fifo   0%  buf  50%
ISO image produced: 578 sectors
Written to media  : 608 sectors at LBA 32
Writing to '/media/hdd/home/thopiekar/Projekte/eclipse-Ultimaker/cura-build-environment/build/AppImageKit-prefix/src/AppImageKit/AppImageAssistant' completed sucessfully.

ok
Embedding runtime...
ok
Embedding magic number 0x414901 at offset 8...
ok
Making /media/hdd/home/thopiekar/Projekte/eclipse-Ultimaker/cura-build-environment/build/AppImageKit-prefix/src/AppImageKit/AppImageAssistant executable...
ok
Size: 1.250000 MB
[ 75%] Built target AppImageAssistant
Scanning dependencies of target AppRun
[ 87%] Building C object CMakeFiles/AppRun.dir/AppRun.c.o
/media/hdd/home/thopiekar/Projekte/eclipse-Ultimaker/cura-build-environment/build/AppImageKit-prefix/src/AppImageKit/AppRun.c: In function 'main':
/media/hdd/home/thopiekar/Projekte/eclipse-Ultimaker/cura-build-environment/build/AppImageKit-prefix/src/AppImageKit/AppRun.c:109:28: warning: passing argument 2 of 'getline' from incompatible pointer type [-Wincompatible-pointer-types]
     while (getline( &line, &n, f ) != -1)
                            ^
In file included from /media/hdd/home/thopiekar/Projekte/eclipse-Ultimaker/cura-build-environment/build/AppImageKit-prefix/src/AppImageKit/AppRun.c:28:0:
/usr/include/stdio.h:680:20: note: expected 'size_t * restrict {aka long unsigned int * restrict}' but argument is of type 'unsigned int *'
 extern _IO_ssize_t getline (char **__restrict __lineptr,
                    ^~~~~~~
[100%] Linking C executable AppRun
[100%] Built target AppRun
Scanning dependencies of target AppImageMonitor
cp: cannot stat '/media/hdd/home/thopiekar/Projekte/eclipse-Ultimaker/cura-build-environment/build/AppImageKit-prefix/src/AppImageKit/binary-dependencies/x86_64/libjte*': No such file or directory
rm: cannot remove './AppImageMonitor': No such file or directory
Creating /media/hdd/home/thopiekar/Projekte/eclipse-Ultimaker/cura-build-environment/build/AppImageKit-prefix/src/AppImageKit/AppImageMonitor ...
xorriso 0.5.6 : RockRidge filesystem manipulator, libburnia project.

xorriso : WARNING : -volid text does not comply to ISO 9660 / ECMA 119 rules
xorriso : UPDATE : Thank you for being patient for 1 seconds
Drive current: -dev '/media/hdd/home/thopiekar/Projekte/eclipse-Ultimaker/cura-build-environment/build/AppImageKit-prefix/src/AppImageKit/AppImageMonitor'
Media current: stdio file, overwriteable
Media status : is blank
Media summary: 0 sessions, 0 data blocks, 0 data,  170g free
Volume id    : 'ISOIMAGE'
New volume id: 'AppImage'
xorriso : UPDATE : 15 files added in 1 seconds
Added to ISO image: directory '/'='/media/hdd/home/thopiekar/Projekte/eclipse-Ultimaker/cura-build-environment/build/AppImageKit-prefix/src/AppImageKit/AppImageMonitor.AppDir'
xorriso : UPDATE : 1 files added in 1 seconds
Added to ISO image: file '/.DirIcon'='/media/hdd/home/thopiekar/Projekte/eclipse-Ultimaker/cura-build-environment/build/AppImageKit-prefix/src/AppImageKit/AppImageMonitor.AppDir/AppImageMonitor.png'
xorriso : UPDATE : 13 file filters processed in 1 seconds
xorriso : UPDATE : Writing:        167s   52.2%   fifo   0%  buf  50%
xorriso : UPDATE : Writing:        242s   75.6%   fifo   0%  buf  50%
ISO image produced: 297 sectors
Written to media  : 320 sectors at LBA 32
Writing to '/media/hdd/home/thopiekar/Projekte/eclipse-Ultimaker/cura-build-environment/build/AppImageKit-prefix/src/AppImageKit/AppImageMonitor' completed sucessfully.

ok
Embedding runtime...
ok
Embedding magic number 0x414901 at offset 8...
ok
Making /media/hdd/home/thopiekar/Projekte/eclipse-Ultimaker/cura-build-environment/build/AppImageKit-prefix/src/AppImageKit/AppImageMonitor executable...
ok
Size: 0.687500 MB
[100%] Built target AppImageMonitor
Scanning dependencies of target AppImageExtract
cp: cannot stat '/media/hdd/home/thopiekar/Projekte/eclipse-Ultimaker/cura-build-environment/build/AppImageKit-prefix/src/AppImageKit/binary-dependencies/x86_64/libjte*': No such file or directory
rm: cannot remove './AppImageExtract': No such file or directory
Creating /media/hdd/home/thopiekar/Projekte/eclipse-Ultimaker/cura-build-environment/build/AppImageKit-prefix/src/AppImageKit/AppImageExtract ...
xorriso 0.5.6 : RockRidge filesystem manipulator, libburnia project.

xorriso : WARNING : -volid text does not comply to ISO 9660 / ECMA 119 rules
xorriso : UPDATE : Thank you for being patient for 1 seconds
Drive current: -dev '/media/hdd/home/thopiekar/Projekte/eclipse-Ultimaker/cura-build-environment/build/AppImageKit-prefix/src/AppImageKit/AppImageExtract'
Media current: stdio file, overwriteable
Media status : is blank
Media summary: 0 sessions, 0 data blocks, 0 data,  170g free
Volume id    : 'ISOIMAGE'
New volume id: 'AppImage'
xorriso : UPDATE : 12 files added in 1 seconds
Added to ISO image: directory '/'='/media/hdd/home/thopiekar/Projekte/eclipse-Ultimaker/cura-build-environment/build/AppImageKit-prefix/src/AppImageKit/AppImageExtract.AppDir'
xorriso : UPDATE : 1 files added in 1 seconds
Added to ISO image: file '/.DirIcon'='/media/hdd/home/thopiekar/Projekte/eclipse-Ultimaker/cura-build-environment/build/AppImageKit-prefix/src/AppImageKit/AppImageExtract.AppDir/AppImageExtract.png'
xorriso : UPDATE : 9 file filters processed in 1 seconds
xorriso : UPDATE : Writing:        157s   54.5%   fifo   0%  buf  50%
ISO image produced: 287 sectors
Written to media  : 288 sectors at LBA 32
Writing to '/media/hdd/home/thopiekar/Projekte/eclipse-Ultimaker/cura-build-environment/build/AppImageKit-prefix/src/AppImageKit/AppImageExtract' completed sucessfully.

ok
Embedding runtime...
ok
Embedding magic number 0x414901 at offset 8...
ok
Making /media/hdd/home/thopiekar/Projekte/eclipse-Ultimaker/cura-build-environment/build/AppImageKit-prefix/src/AppImageKit/AppImageExtract executable...
ok
Size: 0.625000 MB
[100%] Built target AppImageExtract
[100%] Performing install step for 'AppImageKit'
make[4]: *** No rule to make target 'install'.  Stop.
CMakeFiles/AppImageKit.dir/build.make:73: recipe for target 'AppImageKit-prefix/src/AppImageKit-stamp/AppImageKit-install' failed
make[3]: *** [AppImageKit-prefix/src/AppImageKit-stamp/AppImageKit-install] Error 2
CMakeFiles/Makefile2:385: recipe for target 'CMakeFiles/AppImageKit.dir/all' failed
make[2]: *** [CMakeFiles/AppImageKit.dir/all] Error 2
CMakeFiles/Makefile2:397: recipe for target 'CMakeFiles/AppImageKit.dir/rule' failed
make[1]: *** [CMakeFiles/AppImageKit.dir/rule] Error 2
Makefile:222: recipe for target 'AppImageKit' failed
make: *** [AppImageKit] Error 2
```

**Comment by probonopd** [comment] 2016-08-28 12:34
After building, do `ls -l runtime`. If it is larger than 32768 bytes, then your are running into #198.

**Comment by probonopd** [comment] 2016-08-28 12:36
In `CMakeLists.txt`, changing line 19 to `ADD_DEFINITIONS(-g -Os -D_FILE_OFFSET_BITS=64)` (**-Os** = optimize for size), then `make clean`, then `make` seems to work for me - can you confirm?

However, please note that you should ideally use a much older build system to produce your AppImage on, e.g., CentOS 6 or debian oldstable. The resulting AppImages will be compatible with a much wider range of target systems, not just the most recent ones.

**Comment by thopiekar** [comment] 2016-08-28 12:39
```
-rwxrwxr-x 1 thopiekar thopiekar 35064 Aug 28 14:37 runtime
```

**Comment by probonopd** [comment] 2016-08-28 12:41
Duplicate of #198. I will make the change in `CMakeLists.txt` once someone confirms there that it works.

**Closed by probonopd** 2016-08-28 12:41 UTC

**Comment by probonopd** [comment] 2016-08-28 12:55
By the way, are you aware of https://github.com/Ultimaker/cura-build/pull/75?

**Comment by thopiekar** [comment] 2016-08-28 13:10
Yes, we are now working on moving from Debian packages to AppImages.
There is also `cura-build-environment`, which will install everything needed to something like a "chroot". So dependencies, like python modules, AppImage, etc., can be built easily.

**Comment by thopiekar** [comment] 2016-08-28 13:12
See: https://github.com/thopiekar/cura-build-environment/blob/master-environment_split/projects/appimagekit.cmake

Are there any plans to support out-of-tree builds?

**Comment by probonopd** [comment] 2016-08-28 20:49
Re. out-of-tree builds see https://github.com/probonopd/AppImageKit/pull/163
